channels:
  - nodefaults
  - bioconda
  - conda-forge
dependencies:
  # Dependencies for local setup only. Make sure to update meta.yml in bioconda channel.
  - python >= 3.6
  - pip
  - pandas
  - biopython
  - anarci == 2020.04.23
